services:

  DMP\PaginatorBundle\Pagination\Listener\PaginationListener:
    autowire: true
    tags:
      - { name: kernel.event_subscriber }

  DMP\PaginatorBundle\Pagination\Doctrine\QueryBuilderPaginator: ~

  DMP\PaginatorBundle\Pagination\Paginator:
    arguments:
      $paginator: '@DMP\PaginatorBundle\Pagination\Doctrine\QueryBuilderPaginator'

  DMP\PaginatorBundle\Pagination\ArgumentResolver\PaginationArgumentValueResolver:
    arguments:
      $limit: 20
      $maxLimit: 100
      $type: 'query'
    tags:
      - { name: controller.argument_value_resolver }
